### ISSUE TITLE
「脳内マップ」という用語の再検討

### ISSUE THREAD

**Issue by ishiitakeru** [forthelocal/ftl_study#2]
第一回目講義（ https://github.com/forthelocal/ftl_study/blob/master/software_design_lecture/lectures/lecture01_outline.md ）に重要概念として提示した「脳内マップ」という用語がいまいちイケてないのでより適切な言葉を見出したい。

**Comment by 164c** [comment]
英語だと 'Knowledge Structures'、日本語だと'知識構造'が一般的な言葉に近いのかな。
https://www.google.co.jp/search?q=knowledge+structures&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjL082UyfPcAhVHZt4KHf06C8wQ_AUICigB&biw=1260&bih=659

**Comment by ishiitakeru** [comment]
「構造」であることが重要なので「知識構造」で適切な気がしますね。更新します。
