### ISSUE TITLE
getter/setterについて

### ISSUE THREAD

**Issue by 164c** [forthelocal/ftl_study#29]
getter/setterはアンチパターンという考え方がある。何も考えずにsetterやgetterを生やすのは確かに設計の崩壊を招きやすいというのは感覚的にあるが、「その理由」を理解しきれていなので、この辺を深掘りしてほしい。
参考）
https://www.kaitoy.xyz/2015/07/22/getters-setters-evil/

**Comment by ishiitakeru** [comment]
## メモ
* 紹介されている記事は哲学的内容が中心だが、ここで問題にしたいのは機能的な部分。
* ゲッターセッターが多いことで具体的にこういう弊害があり、プログラムの品質がこう落ちる、という先人の研究があればそれをまとめたい。
* 先人の研究を探すところから
